version: '3.9'

services:
  selenoid:
    image: "sskorol/selenoid_chromium_vnc:100.0"
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - ./browsers.json:/etc/selenoid/browsers.json
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      /bin/bash -c "
      Xvfb :99 -screen 0 1920x1080x24 & \
      exec /opt/bin/entry_point.sh"
    networks:
      - selenoid_net

  selenoid-ui:
    image: "cleardevice/selenoid-ui-arm"
    container_name: selenoid_ui
    ports:
      - "9090:8080"
    depends_on:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - selenoid_net

networks:
  selenoid_net:
    driver: bridge
